### ISSUE TITLE
Update for Xcode 10 and Swift 4.x

### ISSUE THREAD

**Issue by vilanovi** [hyperjeff/Accelerate-in-Swift#2]
The Playgrounds are not building anymore. Would be nice to update them to the latest version of Swift and Xcode.

Thanks!

**Comment by RahulBhalley** [comment]
Would it be fine if I open up a pull request for the same? 🙂 @vilanovi @hyperjeff

**Comment by hyperjeff** [comment]
Yeah, I'll try to get this updated. Pull request if you want. I'll push it straight to Xcode 11 / Swift 5.

**Comment by hyperjeff** [comment]
wow, 3 years ago.

**Comment by RahulBhalley** [comment]
> Yeah, I'll try to get this updated. Pull request if you want. I'll push it straight to Xcode 11 / Swift 5.

Hey, I have made a pull request https://github.com/hyperjeff/Accelerate-in-Swift/pull/3 which updates the playgrounds to Swift 5.1 and works with Xcode 11. Please check it out. 😄
